/**
 * Production seed (U8) — run inside the app container after the service is up:
 *   aws ecs execute-command --cluster inbound-demo --task <id> --container app \
 *     --interactive --command "node scripts/prod-seed.mjs"
 *
 * Seeds every app's database in dependency order:
 *   qualify   — firmographics + ICP + 24 eval cases (its own pnpm seed)
 *   scheduler — AEs, schedules, event types, routing form (its own seed)
 *   forms     — published talk-to-sales form (its own seed, prod redirectUrl)
 *   analytics — public write key (matches the task env) + funnel dashboard
 *               (public) + the eval record the accuracy panel reads
 *
 * Idempotent: every step upserts or skips on conflict. Requires
 * DATABASE_URL_BASE + ANALYTICS_PUBLIC_KEY + PUBLIC_URL in the environment.
 */
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";

import postgres from "postgres";

const ROOT = path.resolve(import.meta.dirname, "..");
const DB_BASE = process.env.DATABASE_URL_BASE;
const PUBLIC_KEY = process.env.ANALYTICS_PUBLIC_KEY;
const PUBLIC_URL = (process.env.PUBLIC_URL ?? "").replace(/\/$/, "");
if (!DB_BASE || !PUBLIC_KEY || !PUBLIC_URL) {
  console.error(
    "DATABASE_URL_BASE, ANALYTICS_PUBLIC_KEY, PUBLIC_URL are required",
  );
  process.exit(1);
}

function step(name, fn) {
  console.log(`\n== ${name}`);
  fn();
}

function run(cwd, cmd, args, env = {}) {
  const res = spawnSync(cmd, args, {
    cwd,
    env: { ...process.env, ...env },
    stdio: "inherit",
  });
  if (res.status !== 0)
    throw new Error(`${cmd} ${args.join(" ")} failed in ${cwd}`);
}

step("qualify seed", () => {
  run(path.join(ROOT, "apps/qualify"), "pnpm", ["seed"], {
    DATABASE_URL: `${DB_BASE}/inbound_qualify`,
  });
});

step("scheduler seed", () => {
  run(
    path.join(ROOT, "apps/scheduler"),
    "pnpm",
    ["exec", "tsx", "server/seed/run.ts"],
    {
      DATABASE_URL: `${DB_BASE}/inbound_scheduler`,
    },
  );
});

step("forms seed", () => {
  run(
    path.join(ROOT, "apps/forms"),
    "pnpm",
    ["exec", "tsx", "server/seed/run.ts"],
    {
      DATABASE_URL: `${DB_BASE}/inbound_forms`,
      PUBLIC_URL,
    },
  );
});

const sql = postgres(`${DB_BASE}/inbound_analytics`, { max: 1 });

// Public write key — the value is generated by Terraform (SSM) and injected
// into both this script and the qualify app's env.
await sql`
  INSERT INTO analytics_public_keys (id, name, public_key, public_key_prefix, replay_allowed_origins, replay_max_bytes_per_day, replay_max_requests_per_minute, created_at)
  VALUES (${"apk_seed"}, ${"Inbound funnel (prod seed)"}, ${PUBLIC_KEY}, ${PUBLIC_KEY.slice(0, 12)}, ${"[]"}, ${104857600}, ${120}, ${new Date().toISOString()})
  ON CONFLICT (id) DO NOTHING
`;

// Funnel dashboard, public — the exact config verified in dev (exported to
// apps/analytics/seeds/inbound-funnel.json).
const dashboardConfig = readFileSync(
  path.join(ROOT, "apps/analytics/seeds/inbound-funnel.json"),
  "utf8",
);
await sql`
  INSERT INTO dashboards (id, kind, title, config, owner_email, org_id, visibility, created_at, updated_at)
  VALUES (
    ${"inbound-funnel"}, ${"sql"}, ${"Inbound funnel — lead to booking"},
    ${dashboardConfig}, ${"demo@inbound-demo.test"}, ${null}, ${"public"},
    ${new Date().toISOString()}, ${new Date().toISOString()}
  )
  ON CONFLICT (id) DO UPDATE SET config = EXCLUDED.config, visibility = EXCLUDED.visibility, updated_at = EXCLUDED.updated_at
`;

await sql.end();

// The eval record the accuracy panel reads — copied from the verified dev
// run (same model + prompt hash; rerunning in prod reproduces it).
const qsql = postgres(`${DB_BASE}/inbound_qualify`, { max: 1 });
const evalRow = JSON.parse(
  readFileSync(
    path.join(ROOT, "apps/qualify/seeds/latest-eval-run.json"),
    "utf8",
  ),
);
await qsql`
  INSERT INTO eval_runs (id, model, prompt_hash, case_count, pass_count, accuracy, total_cost_usd, results, created_at)
  VALUES (${evalRow.id}, ${evalRow.model}, ${evalRow.promptHash}, ${evalRow.caseCount}, ${evalRow.passCount}, ${evalRow.accuracy}, ${evalRow.totalCostUsd}, ${evalRow.results}, ${evalRow.createdAt})
  ON CONFLICT (id) DO NOTHING
`;
await qsql.end();

// Emit the eval_completed event so the funnel page's accuracy panel lights up.
// Runs inside the container — hit the local gateway, not the public URL.
await fetch("http://127.0.0.1:8080/analytics/track", {
  method: "POST",
  headers: {
    "content-type": "application/json",
    "x-agent-native-analytics-key": PUBLIC_KEY,
  },
  body: JSON.stringify({
    events: [
      {
        event: "eval_completed",
        anonymousId: evalRow.id,
        properties: {
          app: "qualify",
          accuracy: evalRow.accuracy,
          caseCount: evalRow.caseCount,
          passCount: evalRow.passCount,
          model: evalRow.model,
          promptHash: evalRow.promptHash,
        },
        timestamp: evalRow.createdAt,
      },
    ],
  }),
}).then(async (r) => {
  if (!r.ok) throw new Error(`eval_completed emit failed: ${r.status}`);
  console.log("eval_completed emitted");
});

console.log("\nprod seed complete");
