import {
  ensureAdditiveColumns,
  getDbExec,
  runMigrations,
} from "@agent-native/core/db";
import { getRequestUserEmail } from "@agent-native/core/server";

import { schema } from "../db/index.js";
import initPostgres from "../db/migrations-pg/0000_init-scheduling.sql?raw";
// Generated by `drizzle-kit generate` from server/db/schema.ts. The schema
// helpers pick dialect from DATABASE_URL at load time, so the PG file must be
// generated with a postgres:// DATABASE_URL set (see drizzle.pg.config.ts).
import initSqlite from "../db/migrations/0000_init-scheduling.sql?raw";
import { initSchedulingContext } from "../scheduling-context.js";

function isDrizzleTable(value: unknown): value is object {
  return (
    !!value &&
    typeof value === "object" &&
    Object.getOwnPropertySymbols(value).some((s) =>
      s.toString().includes("drizzle"),
    )
  );
}

const schemaTables = Object.values(schema).filter(isDrizzleTable);

const runSchedulerMigrations = runMigrations(
  [
    {
      version: 1,
      name: "init-scheduling",
      sql: { sqlite: initSqlite, postgres: initPostgres },
    },
  ],
  { table: "scheduler_migrations" },
);

export default async (nitroApp: any): Promise<void> => {
  initSchedulingContext(() => getRequestUserEmail());
  await runSchedulerMigrations(nitroApp);
  try {
    const summary = await ensureAdditiveColumns({
      db: getDbExec(),
      tables: schemaTables,
    });
    if (summary.errors.length > 0) {
      console.warn(
        "[db] ensureAdditiveColumns completed with errors:",
        summary.errors,
      );
    }
  } catch (err) {
    console.warn(
      "[db] ensureAdditiveColumns failed (non-fatal):",
      err instanceof Error ? err.message : err,
    );
  }
};
